"""
C. Application Layer Vectors (101-170)
"""
from typing import Dict, Any, List


def get_application_vectors() -> Dict[int, Dict[str, Any]]:
    """Возвращает все Application Layer векторы (101-170)"""

    vectors = {}

    base_vectors = [
        (101, "Hardcoded API Keys", "Detection of hardcoded API keys", "check_hardcoded_api_keys"),
        (102, "Hardcoded Secrets", "Detection of hardcoded secrets", "check_hardcoded_secrets"),
        (103, "OAuth Misconfiguration", "Check for OAuth misconfiguration", "check_oauth_misconfig"),
        (104, "Token Reuse", "Check for token reuse", "check_token_reuse"),
        (105, "JWT Weak Signing", "Check for weak JWT signing", "check_jwt_weak_signing"),
        (106, "JWT None Algorithm", "Check for JWT None algorithm", "check_jwt_none_alg"),
        (107, "Session Fixation", "Check for session fixation", "check_session_fixation"),
        (108, "CSRF Absent", "Check for missing CSRF protection", "check_csrf_absent"),
        (109, "Insecure Deeplinks", "Check for insecure deep links", "check_insecure_deeplinks"),
        (110, "Exported Activities", "Check for exported activities", "check_exported_activities"),
        (111, "Exported Services", "Check for exported services", "check_exported_services"),
        (112, "Exported Receivers", "Check for exported receivers", "check_exported_receivers"),
        (113, "ContentProvider Exposure", "Check for ContentProvider exposure", "check_contentprovider_exposure"),
        (114, "Backup Flag Enabled", "Check for backup flag enabled", "check_backup_flag_enabled"),
        (115, "Intent Hijacking", "Check for intent hijacking", "check_intent_hijacking"),
        (116, "Hardware Backed Keystore", "Check for hardware-backed keystore", "check_hardware_backed_keystore"),
        (117, "Verified Boot", "Check for verified boot", "check_verified_boot"),
        (118, "Bootloader Unlock", "Check for bootloader unlock", "check_bootloader_unlock"),
        (119, "SQL Injection", "Check for SQL injection", "check_sql_injection"),
        (120, "Command Injection", "Check for command injection", "check_command_injection"),
        (121, "Path Traversal", "Check for path traversal", "check_path_traversal"),
        (122, "XXE Injection", "Check for XXE injection", "check_xxe_injection"),
        (123, "SSRF", "Check for server-side request forgery", "check_ssrf"),
        (124, "Deserialization", "Check for unsafe deserialization", "check_deserialization"),
        (125, "XSS", "Check for XSS vulnerabilities", "check_xss"),
        (126, "Insecure Data Storage", "Check for insecure data storage", "check_insecure_data_storage"),
        (127, "Weak Cryptography", "Check for weak cryptography", "check_weak_cryptography"),
        (128, "Insecure Random", "Check for insecure random number generation", "check_insecure_random"),
        (129, "Certificate Pinning", "Check for certificate pinning", "check_certificate_pinning"),
        (130, "Cleartext Traffic", "Check for cleartext traffic", "check_cleartext_traffic"),
        (131, "WebView RCE", "Check for WebView RCE", "check_webview_rce"),
        (132, "File Upload", "Check for file upload vulnerabilities", "check_file_upload"),
        (133, "Directory Listing", "Check for directory listing", "check_directory_listing"),
        (134, "Information Disclosure", "Check for information disclosure", "check_information_disclosure"),
        (135, "Race Conditions", "Check for race conditions", "check_race_conditions"),
        (136, "Memory Corruption", "Check for memory corruption", "check_memory_corruption"),
        (137, "Buffer Overflow", "Check for buffer overflow", "check_buffer_overflow"),
        (138, "Integer Overflow", "Check for integer overflow", "check_integer_overflow"),
        (139, "Format String", "Check for format string vulnerabilities", "check_format_string"),
        (140, "Use After Free", "Check for use after free", "check_use_after_free"),
        (141, "Double Free", "Check for double free", "check_double_free"),
        (142, "Dangling Pointer", "Check for dangling pointer", "check_dangling_pointer"),
        (143, "Type Confusion", "Check for type confusion", "check_type_confusion"),
        (144, "TOCTOU", "Check for time-of-check to time-of-use", "check_toctou"),
        (145, "Missing Authorization", "Check for missing authorization", "check_missing_authorization"),
        (146, "Broken Authentication", "Check for broken authentication", "check_broken_authentication"),
        (147, "Privilege Escalation", "Check for privilege escalation", "check_privilege_escalation"),
        (148, "IDOR", "Check for insecure direct object reference", "check_idor"),
        (149, "Security Misconfiguration", "Check for security misconfiguration", "check_security_misconfig"),
        (150, "Components with Tabs", "Check for components with tabs", "check_components_with_tabs"),
        (151, "PendingIntents", "Check for PendingIntents vulnerabilities", "check_pendingints"),
        (152, "Shared Preferences", "Check for shared preferences issues", "check_shared_preferences"),
        (153, "External Storage", "Check for external storage issues", "check_external_storage"),
        (154, "SQLite Database", "Check for SQLite database issues", "check_sqlite_database"),
        (155, "Log Sensitive Data", "Check for sensitive data in logs", "check_log_sensitive_data"),
        (156, "Broadcast Intents", "Check for broadcast intents issues", "check_broadcast_intents"),
        (157, "Services", "Check for service issues", "check_services"),
        (158, "Content Providers", "Check for content provider issues", "check_content_providers"),
        (159, "File Providers", "Check for file provider issues", "check_file_providers"),
        (160, "Activities", "Check for activity issues", "check_activities"),
        (161, "Receivers", "Check for receiver issues", "check_receivers"),
        (162, "Providers", "Check for provider issues", "check_providers"),
        (163, "Deep Links", "Check for deep link issues", "check_deep_links"),
        (164, "App Links", "Check for app link issues", "check_app_links"),
        (165, "WebSockets", "Check for WebSocket issues", "check_websockets"),
        (166, "Push Notifications", "Check for push notification issues", "check_push_notifications"),
        (167, "Background Services", "Check for background service issues", "check_background_services"),
        (168, "Foreground Services", "Check for foreground service issues", "check_foreground_services"),
        (169, "Job Scheduler", "Check for job scheduler issues", "check_job_scheduler"),
        (170, "Work Manager", "Check for work manager issues", "check_work_manager"),
    ]

    for vector_id, name, description, check_func in base_vectors:
        vectors[vector_id] = {
            "id": vector_id,
            "category": "C",
            "name": name,
            "description": description,
            "check_function": check_func,
            "requires_adb": True,
            "requires_network": False,
            "priority": 3,
            "depends_on": [6],
            "tags": ["application", "app", "software"],
            "severity": "INFO",
            "weights": None,
            "confirmed_threshold": 0.7,
            "inconclusive_threshold": 0.4,
        }

    return vectors
