"""aasfa.vectors.crypto_api_vectors

Дополнительные векторы (часть 2):
- Cryptography (5000-5049)
- API Security (5100-5149)

Векторная модель в проекте использует структуру, совместимую с VectorRegistry:
каждая запись должна содержать ключи:
- id, category, name, description, check_functions, requires_adb, requires_network,
  priority, depends_on, tags, severity

Дополнительно можно указывать cvss_score / remediation / references.
"""

from __future__ import annotations

from typing import Any, Dict


def get_crypto_api_vectors() -> Dict[int, Dict[str, Any]]:
    """Возвращает Crypto + API векторы."""

    vectors: Dict[int, Dict[str, Any]] = {
    5000: {
        "id": 5000,
        "category": 'Cryptography',
        "name": 'MD5 Hash Usage (Static)',
        "description": 'MD5 используется в коде для хеширования. Алгоритм уязвим к коллизиям и rainbow tables.',
        "check_functions": ['check_md5_usage', 'check_weak_password_hashing'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'hash', 'static'],
        "severity": 'HIGH',
        "cvss_score": 7.4,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Заменить MD5 на SHA-256/512. Для паролей использовать bcrypt/scrypt/argon2.',
        "references": ['https://www.rfc-editor.org/rfc/rfc6151'],
    },
    5001: {
        "id": 5001,
        "category": 'Cryptography',
        "name": 'SHA1 Hash Usage (Static)',
        "description": 'SHA-1 используется в коде. Известны практические коллизии.',
        "check_functions": ['check_sha1_usage', 'check_weak_password_hashing'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'hash', 'static'],
        "severity": 'HIGH',
        "cvss_score": 7.1,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Заменить SHA-1 на SHA-256/512. Для подписи использовать современные алгоритмы.',
        "references": ['https://shattered.io/'],
    },
    5002: {
        "id": 5002,
        "category": 'Cryptography',
        "name": 'DES / 3DES Usage (Static)',
        "description": 'DES/3DES обнаружен в коде. 56-bit ключ подбирается, 3DES считается устаревшим.',
        "check_functions": ['check_des_usage', 'check_insecure_crypto_modes_general'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 1,
        "depends_on": [],
        "tags": ['crypto', 'cipher', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 9.0,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Использовать AES-GCM/ChaCha20-Poly1305. Исключить DES/3DES из конфигураций.',
        "references": ['https://sweet32.info/'],
    },
    5003: {
        "id": 5003,
        "category": 'Cryptography',
        "name": 'RC4 Usage (Static)',
        "description": 'RC4 обнаружен в коде или конфигурации. Известны атаки на потоковый шифр.',
        "check_functions": ['check_rc4_usage', 'check_insecure_crypto_modes_general'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 1,
        "depends_on": [],
        "tags": ['crypto', 'cipher', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 9.0,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Отключить RC4. Использовать TLS 1.2+ и современные шифры.',
        "references": ['https://datatracker.ietf.org/doc/html/rfc7465'],
    },
    5004: {
        "id": 5004,
        "category": 'Cryptography',
        "name": 'MD4 Usage (Static)',
        "description": 'MD4 является крайне устаревшим и не должен использоваться.',
        "check_functions": ['check_md4_usage', 'check_insecure_crypto_modes_general'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 1,
        "depends_on": [],
        "tags": ['crypto', 'hash', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 9.0,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Удалить MD4. Использовать SHA-256/512.',
        "references": ['https://csrc.nist.gov/projects/hash-functions'],
    },
    5005: {
        "id": 5005,
        "category": 'Cryptography',
        "name": 'Hardcoded Keys / Secrets (Static)',
        "description": 'В коде обнаружены признаки захардкоженных секретов/ключей.',
        "check_functions": ['check_hardcoded_keys', 'check_hardcoded_secret_01'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 1,
        "depends_on": [],
        "tags": ['crypto', 'secrets', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 9.5,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убрать секреты из репозитория. Использовать секрет-менеджер/переменные окружения. Ротировать ключи.',
        "references": ['https://12factor.net/config'],
    },
    5006: {
        "id": 5006,
        "category": 'Cryptography',
        "name": 'TLS 1.0/1.1 Supported',
        "description": 'Сервер принимает устаревшие версии TLS (TLS 1.0/1.1).',
        "check_functions": ['check_tls_version_old', 'check_weak_cipher_suites'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 1,
        "depends_on": [],
        "tags": ['crypto', 'tls', 'network'],
        "severity": 'HIGH',
        "cvss_score": 7.5,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Отключить TLS 1.0/1.1. Включить TLS 1.2/1.3.',
        "references": ['https://cheatsheetseries.owasp.org/cheatsheets/Transport_Layer_Protection_Cheat_Sheet.html'],
    },
    5007: {
        "id": 5007,
        "category": 'Cryptography',
        "name": 'Weak TLS Cipher Suites',
        "description": 'Обнаружены слабые cipher suites (RC4/DES/NULL/EXPORT/MD5).',
        "check_functions": ['check_weak_cipher_suites', 'check_tls_no_forward_secrecy'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 1,
        "depends_on": [],
        "tags": ['crypto', 'tls', 'network'],
        "severity": 'HIGH',
        "cvss_score": 7.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Отключить слабые шифры. Разрешить только современные AEAD (AES-GCM, ChaCha20-Poly1305) с ECDHE.',
        "references": ['https://wiki.mozilla.org/Security/Server_Side_TLS'],
    },
    5008: {
        "id": 5008,
        "category": 'Cryptography',
        "name": 'Self-Signed Certificate',
        "description": 'Используется самоподписанный сертификат. Возможны MITM атаки.',
        "check_functions": ['check_self_signed_cert', 'check_cert_weak_signature'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'tls', 'cert'],
        "severity": 'MEDIUM',
        "cvss_score": 5.9,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Использовать сертификат от доверенного CA. Для устройств — предусмотреть корректный trust-store.',
        "references": ['https://letsencrypt.org/'],
    },
    5009: {
        "id": 5009,
        "category": 'Cryptography',
        "name": 'Certificate Expiration / Soon Expiring',
        "description": 'Сертификат истёк или истекает в ближайшие дни.',
        "check_functions": ['check_cert_expiration', 'check_self_signed_cert'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'tls', 'cert'],
        "severity": 'MEDIUM',
        "cvss_score": 5.3,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Обновить сертификат и настроить автоматическую ротацию/renew.',
        "references": ['https://datatracker.ietf.org/doc/html/rfc5280'],
    },
    5010: {
        "id": 5010,
        "category": 'Cryptography',
        "name": 'Weak RSA Key Length (<2048)',
        "description": 'Ключ сертификата RSA короче 2048 бит.',
        "check_functions": ['check_rsa_key_length', 'check_cert_weak_signature'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 1,
        "depends_on": [],
        "tags": ['crypto', 'tls', 'cert'],
        "severity": 'HIGH',
        "cvss_score": 7.4,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Перевыпустить сертификат с RSA 2048+ (лучше 3072+) или ECDSA P-256/P-384.',
        "references": ['https://www.keylength.com/'],
    },
    5011: {
        "id": 5011,
        "category": 'Cryptography',
        "name": 'Weak Certificate Signature (MD5/SHA1)',
        "description": 'Сертификат подписан слабым алгоритмом (MD5/SHA1).',
        "check_functions": ['check_cert_weak_signature', 'check_tls_version_old'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 1,
        "depends_on": [],
        "tags": ['crypto', 'tls', 'cert'],
        "severity": 'HIGH',
        "cvss_score": 7.0,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Перевыпустить сертификат с подписью SHA-256+.',
        "references": ['https://csrc.nist.gov/publications/detail/sp/800-131a/rev-2/final'],
    },
    5012: {
        "id": 5012,
        "category": 'Cryptography',
        "name": 'No Forward Secrecy',
        "description": 'Negotiated TLS cipher не содержит (EC)DHE — вероятно отсутствует Forward Secrecy.',
        "check_functions": ['check_tls_no_forward_secrecy', 'check_weak_cipher_suites'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'tls', 'network'],
        "severity": 'MEDIUM',
        "cvss_score": 6.0,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Включить ECDHE/DHE. Использовать современные настройки TLS.',
        "references": ['https://wiki.mozilla.org/Security/Server_Side_TLS'],
    },
    5013: {
        "id": 5013,
        "category": 'Cryptography',
        "name": 'TLS Verification Disabled (Static)',
        "description": 'В коде обнаружены признаки отключения проверки TLS сертификата (verify=False, CERT_NONE).',
        "check_functions": ['check_tls_verification_disabled', 'check_insecure_crypto_modes_general'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 1,
        "depends_on": [],
        "tags": ['crypto', 'tls', 'static'],
        "severity": 'HIGH',
        "cvss_score": 8.0,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Включить verify_mode=CERT_REQUIRED и проверку hostname. Не использовать unverified contexts.',
        "references": ['https://docs.python.org/3/library/ssl.html#best-practices'],
    },
    5014: {
        "id": 5014,
        "category": 'Cryptography',
        "name": 'Insecure RNG in Crypto Context (Static)',
        "description": 'Используется random()/Math.random() вместо криптостойкого генератора.',
        "check_functions": ['check_insecure_random_usage', 'check_insecure_crypto_modes_general'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'rng', 'static'],
        "severity": 'MEDIUM',
        "cvss_score": 6.2,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Использовать secrets/os.urandom/SecureRandom для ключей, nonce, salt.',
        "references": ['https://docs.python.org/3/library/secrets.html'],
    },
    5015: {
        "id": 5015,
        "category": 'Cryptography',
        "name": 'AES ECB Mode (Static)',
        "description": 'Режим ECB раскрывает структуру данных и не подходит для шифрования.',
        "check_functions": ['check_ecb_mode_usage', 'check_static_iv_usage'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 1,
        "depends_on": [],
        "tags": ['crypto', 'cipher', 'static'],
        "severity": 'HIGH',
        "cvss_score": 7.0,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Использовать AEAD (AES-GCM/ChaCha20-Poly1305).',
        "references": ['https://cheatsheetseries.owasp.org/cheatsheets/Cryptographic_Storage_Cheat_Sheet.html'],
    },
    5016: {
        "id": 5016,
        "category": 'Cryptography',
        "name": 'Static IV (Static)',
        "description": 'Статический IV приводит к утечке информации и повторному использованию nonce.',
        "check_functions": ['check_static_iv_usage', 'check_insecure_random_usage'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 1,
        "depends_on": [],
        "tags": ['crypto', 'cipher', 'static'],
        "severity": 'HIGH',
        "cvss_score": 7.2,
        "exploitation_difficulty": 'Medium',
        "remediation": 'IV/nonce должен быть уникальным и непредсказуемым. Генерировать cryptographically secure random.',
        "references": ['https://crypto.stackexchange.com/questions/2371'],
    },
    5017: {
        "id": 5017,
        "category": 'Cryptography',
        "name": 'Weak PBKDF2 Iterations (Static)',
        "description": 'PBKDF2 используется с низким числом итераций (риск ускоренного brute force).',
        "check_functions": ['check_weak_kdf_iterations', 'check_password_hashing'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'kdf', 'static'],
        "severity": 'MEDIUM',
        "cvss_score": 6.0,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Увеличить iterations согласно рекомендациям (OWASP/актуальная политика). Рассмотреть argon2.',
        "references": ['https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html'],
    },
    5018: {
        "id": 5018,
        "category": 'Cryptography',
        "name": 'Weak / Missing Salt (Static)',
        "description": 'Вероятно отсутствует salt при хешировании паролей.',
        "check_functions": ['check_salt_usage', 'check_password_hashing'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'password', 'static'],
        "severity": 'MEDIUM',
        "cvss_score": 5.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Использовать уникальный salt для каждого пароля и стойкий KDF.',
        "references": ['https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html'],
    },
    5019: {
        "id": 5019,
        "category": 'Cryptography',
        "name": 'SSL Pinning Missing (Static)',
        "description": 'Сетевые вызовы присутствуют, но pinning не обнаружен. Риск MITM на недоверенных сетях.',
        "check_functions": ['check_ssl_pinning', 'check_tls_verification_disabled'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['crypto', 'tls', 'mobile', 'static'],
        "severity": 'LOW',
        "cvss_score": 4.3,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Для мобильных/IoT клиентов рассмотреть certificate/public key pinning + корректная ротация.',
        "references": ['https://owasp.org/www-project-mobile-security/'],
    },
    5020: {
        "id": 5020,
        "category": 'Cryptography',
        "name": 'Hardcoded Secret Pattern #01',
        "description": 'Дополнительная эвристика поиска секретов в исходном коде (переменные окружения/конфиги).',
        "check_functions": ['check_hardcoded_secret_02', 'check_hardcoded_keys'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'secrets', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 8.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Удалить секреты из кода, использовать secret manager и выполнить ротацию.',
        "references": ['https://owasp.org/www-project-top-ten/'],
    },
    5021: {
        "id": 5021,
        "category": 'Cryptography',
        "name": 'Hardcoded Secret Pattern #02',
        "description": 'Дополнительная эвристика поиска секретов в исходном коде (переменные окружения/конфиги).',
        "check_functions": ['check_hardcoded_secret_03', 'check_hardcoded_keys'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'secrets', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 8.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Удалить секреты из кода, использовать secret manager и выполнить ротацию.',
        "references": ['https://owasp.org/www-project-top-ten/'],
    },
    5022: {
        "id": 5022,
        "category": 'Cryptography',
        "name": 'Hardcoded Secret Pattern #03',
        "description": 'Дополнительная эвристика поиска секретов в исходном коде (переменные окружения/конфиги).',
        "check_functions": ['check_hardcoded_secret_04', 'check_hardcoded_keys'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'secrets', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 8.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Удалить секреты из кода, использовать secret manager и выполнить ротацию.',
        "references": ['https://owasp.org/www-project-top-ten/'],
    },
    5023: {
        "id": 5023,
        "category": 'Cryptography',
        "name": 'Hardcoded Secret Pattern #04',
        "description": 'Дополнительная эвристика поиска секретов в исходном коде (переменные окружения/конфиги).',
        "check_functions": ['check_hardcoded_secret_05', 'check_hardcoded_keys'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'secrets', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 8.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Удалить секреты из кода, использовать secret manager и выполнить ротацию.',
        "references": ['https://owasp.org/www-project-top-ten/'],
    },
    5024: {
        "id": 5024,
        "category": 'Cryptography',
        "name": 'Hardcoded Secret Pattern #05',
        "description": 'Дополнительная эвристика поиска секретов в исходном коде (переменные окружения/конфиги).',
        "check_functions": ['check_hardcoded_secret_06', 'check_hardcoded_keys'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'secrets', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 8.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Удалить секреты из кода, использовать secret manager и выполнить ротацию.',
        "references": ['https://owasp.org/www-project-top-ten/'],
    },
    5025: {
        "id": 5025,
        "category": 'Cryptography',
        "name": 'Hardcoded Secret Pattern #06',
        "description": 'Дополнительная эвристика поиска секретов в исходном коде (переменные окружения/конфиги).',
        "check_functions": ['check_hardcoded_secret_07', 'check_hardcoded_keys'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'secrets', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 8.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Удалить секреты из кода, использовать secret manager и выполнить ротацию.',
        "references": ['https://owasp.org/www-project-top-ten/'],
    },
    5026: {
        "id": 5026,
        "category": 'Cryptography',
        "name": 'Hardcoded Secret Pattern #07',
        "description": 'Дополнительная эвристика поиска секретов в исходном коде (переменные окружения/конфиги).',
        "check_functions": ['check_hardcoded_secret_08', 'check_hardcoded_keys'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'secrets', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 8.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Удалить секреты из кода, использовать secret manager и выполнить ротацию.',
        "references": ['https://owasp.org/www-project-top-ten/'],
    },
    5027: {
        "id": 5027,
        "category": 'Cryptography',
        "name": 'Hardcoded Secret Pattern #08',
        "description": 'Дополнительная эвристика поиска секретов в исходном коде (переменные окружения/конфиги).',
        "check_functions": ['check_hardcoded_secret_09', 'check_hardcoded_keys'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'secrets', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 8.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Удалить секреты из кода, использовать secret manager и выполнить ротацию.',
        "references": ['https://owasp.org/www-project-top-ten/'],
    },
    5028: {
        "id": 5028,
        "category": 'Cryptography',
        "name": 'Hardcoded Secret Pattern #09',
        "description": 'Дополнительная эвристика поиска секретов в исходном коде (переменные окружения/конфиги).',
        "check_functions": ['check_hardcoded_secret_10', 'check_hardcoded_keys'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'secrets', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 8.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Удалить секреты из кода, использовать secret manager и выполнить ротацию.',
        "references": ['https://owasp.org/www-project-top-ten/'],
    },
    5029: {
        "id": 5029,
        "category": 'Cryptography',
        "name": 'Hardcoded Secret Pattern #10',
        "description": 'Дополнительная эвристика поиска секретов в исходном коде (переменные окружения/конфиги).',
        "check_functions": ['check_hardcoded_secret_11', 'check_hardcoded_keys'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'secrets', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 8.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Удалить секреты из кода, использовать secret manager и выполнить ротацию.',
        "references": ['https://owasp.org/www-project-top-ten/'],
    },
    5030: {
        "id": 5030,
        "category": 'Cryptography',
        "name": 'Hardcoded Secret Pattern #11',
        "description": 'Дополнительная эвристика поиска секретов в исходном коде (переменные окружения/конфиги).',
        "check_functions": ['check_hardcoded_secret_12', 'check_hardcoded_keys'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'secrets', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 8.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Удалить секреты из кода, использовать secret manager и выполнить ротацию.',
        "references": ['https://owasp.org/www-project-top-ten/'],
    },
    5031: {
        "id": 5031,
        "category": 'Cryptography',
        "name": 'Hardcoded Secret Pattern #12',
        "description": 'Дополнительная эвристика поиска секретов в исходном коде (переменные окружения/конфиги).',
        "check_functions": ['check_hardcoded_secret_13', 'check_hardcoded_keys'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'secrets', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 8.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Удалить секреты из кода, использовать secret manager и выполнить ротацию.',
        "references": ['https://owasp.org/www-project-top-ten/'],
    },
    5032: {
        "id": 5032,
        "category": 'Cryptography',
        "name": 'Hardcoded Secret Pattern #13',
        "description": 'Дополнительная эвристика поиска секретов в исходном коде (переменные окружения/конфиги).',
        "check_functions": ['check_hardcoded_secret_14', 'check_hardcoded_keys'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'secrets', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 8.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Удалить секреты из кода, использовать secret manager и выполнить ротацию.',
        "references": ['https://owasp.org/www-project-top-ten/'],
    },
    5033: {
        "id": 5033,
        "category": 'Cryptography',
        "name": 'Hardcoded Secret Pattern #14',
        "description": 'Дополнительная эвристика поиска секретов в исходном коде (переменные окружения/конфиги).',
        "check_functions": ['check_hardcoded_secret_01', 'check_hardcoded_keys'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'secrets', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 8.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Удалить секреты из кода, использовать secret manager и выполнить ротацию.',
        "references": ['https://owasp.org/www-project-top-ten/'],
    },
    5034: {
        "id": 5034,
        "category": 'Cryptography',
        "name": 'Hardcoded Secret Pattern #15',
        "description": 'Дополнительная эвристика поиска секретов в исходном коде (переменные окружения/конфиги).',
        "check_functions": ['check_hardcoded_secret_02', 'check_hardcoded_keys'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'secrets', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 8.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Удалить секреты из кода, использовать secret manager и выполнить ротацию.',
        "references": ['https://owasp.org/www-project-top-ten/'],
    },
    5035: {
        "id": 5035,
        "category": 'Cryptography',
        "name": 'Hardcoded Secret Pattern #16',
        "description": 'Дополнительная эвристика поиска секретов в исходном коде (переменные окружения/конфиги).',
        "check_functions": ['check_hardcoded_secret_03', 'check_hardcoded_keys'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'secrets', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 8.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Удалить секреты из кода, использовать secret manager и выполнить ротацию.',
        "references": ['https://owasp.org/www-project-top-ten/'],
    },
    5036: {
        "id": 5036,
        "category": 'Cryptography',
        "name": 'Hardcoded Secret Pattern #17',
        "description": 'Дополнительная эвристика поиска секретов в исходном коде (переменные окружения/конфиги).',
        "check_functions": ['check_hardcoded_secret_04', 'check_hardcoded_keys'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'secrets', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 8.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Удалить секреты из кода, использовать secret manager и выполнить ротацию.',
        "references": ['https://owasp.org/www-project-top-ten/'],
    },
    5037: {
        "id": 5037,
        "category": 'Cryptography',
        "name": 'Hardcoded Secret Pattern #18',
        "description": 'Дополнительная эвристика поиска секретов в исходном коде (переменные окружения/конфиги).',
        "check_functions": ['check_hardcoded_secret_05', 'check_hardcoded_keys'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'secrets', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 8.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Удалить секреты из кода, использовать secret manager и выполнить ротацию.',
        "references": ['https://owasp.org/www-project-top-ten/'],
    },
    5038: {
        "id": 5038,
        "category": 'Cryptography',
        "name": 'Hardcoded Secret Pattern #19',
        "description": 'Дополнительная эвристика поиска секретов в исходном коде (переменные окружения/конфиги).',
        "check_functions": ['check_hardcoded_secret_06', 'check_hardcoded_keys'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'secrets', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 8.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Удалить секреты из кода, использовать secret manager и выполнить ротацию.',
        "references": ['https://owasp.org/www-project-top-ten/'],
    },
    5039: {
        "id": 5039,
        "category": 'Cryptography',
        "name": 'Hardcoded Secret Pattern #20',
        "description": 'Дополнительная эвристика поиска секретов в исходном коде (переменные окружения/конфиги).',
        "check_functions": ['check_hardcoded_secret_07', 'check_hardcoded_keys'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'secrets', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 8.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Удалить секреты из кода, использовать secret manager и выполнить ротацию.',
        "references": ['https://owasp.org/www-project-top-ten/'],
    },
    5040: {
        "id": 5040,
        "category": 'Cryptography',
        "name": 'Hardcoded Secret Pattern #21',
        "description": 'Дополнительная эвристика поиска секретов в исходном коде (переменные окружения/конфиги).',
        "check_functions": ['check_hardcoded_secret_08', 'check_hardcoded_keys'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'secrets', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 8.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Удалить секреты из кода, использовать secret manager и выполнить ротацию.',
        "references": ['https://owasp.org/www-project-top-ten/'],
    },
    5041: {
        "id": 5041,
        "category": 'Cryptography',
        "name": 'Hardcoded Secret Pattern #22',
        "description": 'Дополнительная эвристика поиска секретов в исходном коде (переменные окружения/конфиги).',
        "check_functions": ['check_hardcoded_secret_09', 'check_hardcoded_keys'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'secrets', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 8.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Удалить секреты из кода, использовать secret manager и выполнить ротацию.',
        "references": ['https://owasp.org/www-project-top-ten/'],
    },
    5042: {
        "id": 5042,
        "category": 'Cryptography',
        "name": 'Hardcoded Secret Pattern #23',
        "description": 'Дополнительная эвристика поиска секретов в исходном коде (переменные окружения/конфиги).',
        "check_functions": ['check_hardcoded_secret_10', 'check_hardcoded_keys'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'secrets', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 8.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Удалить секреты из кода, использовать secret manager и выполнить ротацию.',
        "references": ['https://owasp.org/www-project-top-ten/'],
    },
    5043: {
        "id": 5043,
        "category": 'Cryptography',
        "name": 'Hardcoded Secret Pattern #24',
        "description": 'Дополнительная эвристика поиска секретов в исходном коде (переменные окружения/конфиги).',
        "check_functions": ['check_hardcoded_secret_11', 'check_hardcoded_keys'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'secrets', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 8.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Удалить секреты из кода, использовать secret manager и выполнить ротацию.',
        "references": ['https://owasp.org/www-project-top-ten/'],
    },
    5044: {
        "id": 5044,
        "category": 'Cryptography',
        "name": 'Hardcoded Secret Pattern #25',
        "description": 'Дополнительная эвристика поиска секретов в исходном коде (переменные окружения/конфиги).',
        "check_functions": ['check_hardcoded_secret_12', 'check_hardcoded_keys'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'secrets', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 8.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Удалить секреты из кода, использовать secret manager и выполнить ротацию.',
        "references": ['https://owasp.org/www-project-top-ten/'],
    },
    5045: {
        "id": 5045,
        "category": 'Cryptography',
        "name": 'Hardcoded Secret Pattern #26',
        "description": 'Дополнительная эвристика поиска секретов в исходном коде (переменные окружения/конфиги).',
        "check_functions": ['check_hardcoded_secret_13', 'check_hardcoded_keys'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'secrets', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 8.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Удалить секреты из кода, использовать secret manager и выполнить ротацию.',
        "references": ['https://owasp.org/www-project-top-ten/'],
    },
    5046: {
        "id": 5046,
        "category": 'Cryptography',
        "name": 'Hardcoded Secret Pattern #27',
        "description": 'Дополнительная эвристика поиска секретов в исходном коде (переменные окружения/конфиги).',
        "check_functions": ['check_hardcoded_secret_14', 'check_hardcoded_keys'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'secrets', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 8.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Удалить секреты из кода, использовать secret manager и выполнить ротацию.',
        "references": ['https://owasp.org/www-project-top-ten/'],
    },
    5047: {
        "id": 5047,
        "category": 'Cryptography',
        "name": 'Hardcoded Secret Pattern #28',
        "description": 'Дополнительная эвристика поиска секретов в исходном коде (переменные окружения/конфиги).',
        "check_functions": ['check_hardcoded_secret_01', 'check_hardcoded_keys'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'secrets', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 8.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Удалить секреты из кода, использовать secret manager и выполнить ротацию.',
        "references": ['https://owasp.org/www-project-top-ten/'],
    },
    5048: {
        "id": 5048,
        "category": 'Cryptography',
        "name": 'Hardcoded Secret Pattern #29',
        "description": 'Дополнительная эвристика поиска секретов в исходном коде (переменные окружения/конфиги).',
        "check_functions": ['check_hardcoded_secret_02', 'check_hardcoded_keys'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'secrets', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 8.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Удалить секреты из кода, использовать secret manager и выполнить ротацию.',
        "references": ['https://owasp.org/www-project-top-ten/'],
    },
    5049: {
        "id": 5049,
        "category": 'Cryptography',
        "name": 'Hardcoded Secret Pattern #30',
        "description": 'Дополнительная эвристика поиска секретов в исходном коде (переменные окружения/конфиги).',
        "check_functions": ['check_hardcoded_secret_03', 'check_hardcoded_keys'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['crypto', 'secrets', 'static'],
        "severity": 'CRITICAL',
        "cvss_score": 8.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Удалить секреты из кода, использовать secret manager и выполнить ротацию.',
        "references": ['https://owasp.org/www-project-top-ten/'],
    },
    5100: {
        "id": 5100,
        "category": 'API',
        "name": 'API Without Authentication',
        "description": 'API endpoints доступны без аутентификации. Это часто приводит к полной утечке данных.',
        "check_functions": ['check_api_authentication', 'check_api_admin_panels_exposed'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 1,
        "depends_on": [],
        "tags": ['api', 'auth', 'network'],
        "severity": 'CRITICAL',
        "cvss_score": 9.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Включить аутентификацию (JWT/OAuth2/mTLS) и строгую авторизацию на каждом endpoint.',
        "references": ['https://cheatsheetseries.owasp.org/cheatsheets/REST_Security_Cheat_Sheet.html'],
    },
    5101: {
        "id": 5101,
        "category": 'API',
        "name": 'API Without HTTPS',
        "description": 'API работает по HTTP без шифрования. Трафик может быть перехвачен.',
        "check_functions": ['check_api_no_https', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 1,
        "depends_on": [],
        "tags": ['api', 'tls', 'network'],
        "severity": 'CRITICAL',
        "cvss_score": 9.1,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Перевести API на HTTPS. Включить HSTS на web-части, запретить downgrade.',
        "references": ['https://cheatsheetseries.owasp.org/cheatsheets/Transport_Layer_Protection_Cheat_Sheet.html'],
    },
    5102: {
        "id": 5102,
        "category": 'API',
        "name": 'No Rate Limiting',
        "description": 'Отсутствие rate limiting позволяет brute force и DoS.',
        "check_functions": ['check_api_rate_limiting', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['api', 'dos', 'bruteforce'],
        "severity": 'MEDIUM',
        "cvss_score": 6.5,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Добавить rate limiting на уровне gateway/WAF и per-user/per-IP квоты.',
        "references": ['https://cheatsheetseries.owasp.org/cheatsheets/Denial_of_Service_Cheat_Sheet.html'],
    },
    5103: {
        "id": 5103,
        "category": 'API',
        "name": 'CORS Wildcard',
        "description": 'CORS настроен с wildcard (*). Любой сайт может читать ответы API при определённых условиях.',
        "check_functions": ['check_cors_wildcard', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['api', 'cors', 'browser'],
        "severity": 'HIGH',
        "cvss_score": 7.0,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Ограничить Access-Control-Allow-Origin конкретными доменами. Не включать credentials вместе с *.',
        "references": ['https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS'],
    },
    5104: {
        "id": 5104,
        "category": 'API',
        "name": 'API Documentation / OpenAPI Exposure',
        "description": 'Swagger/OpenAPI документация доступна публично и может раскрывать структуру API.',
        "check_functions": ['check_api_info_disclosure', 'check_api_swagger_exposed'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['api', 'disclosure'],
        "severity": 'HIGH',
        "cvss_score": 6.8,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Ограничить доступ к swagger/openapi (auth, allow-list) или отключить в production.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5105: {
        "id": 5105,
        "category": 'API',
        "name": 'Default Credentials',
        "description": 'API принимает дефолтные логины/пароли.',
        "check_functions": ['check_api_default_credentials', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 1,
        "depends_on": [],
        "tags": ['api', 'auth', 'passwords'],
        "severity": 'CRITICAL',
        "cvss_score": 9.6,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Удалить/заблокировать дефолтные аккаунты, enforce смену пароля при первом входе, MFA.',
        "references": ['https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html'],
    },
    5106: {
        "id": 5106,
        "category": 'API',
        "name": 'Weak JWT Secret / alg=none',
        "description": 'JWT токены могут быть подделаны при слабом секрете или alg=none.',
        "check_functions": ['check_jwt_weak_secret', 'check_api_default_credentials'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 1,
        "depends_on": [],
        "tags": ['api', 'jwt', 'auth'],
        "severity": 'CRITICAL',
        "cvss_score": 9.1,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Использовать сильный секрет или асимметричную подпись (RS256/ES256), включить аудит claims (exp, aud, iss).',
        "references": ['https://datatracker.ietf.org/doc/html/rfc7519'],
    },
    5107: {
        "id": 5107,
        "category": 'API',
        "name": 'Potential SQL Injection',
        "description": 'В ответах API обнаружены маркеры SQL ошибок при вводе инъекционных payload.',
        "check_functions": ['check_api_sql_injection', 'check_api_error_messages'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 1,
        "depends_on": [],
        "tags": ['api', 'sqli'],
        "severity": 'HIGH',
        "cvss_score": 8.6,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Использовать параметризованные запросы/ORM, валидировать ввод, отключить verbose ошибки.',
        "references": ['https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html'],
    },
    5108: {
        "id": 5108,
        "category": 'API',
        "name": 'Potential IDOR',
        "description": 'Доступ к объектам по ID возможен без корректной авторизации.',
        "check_functions": ['check_api_idor', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 1,
        "depends_on": [],
        "tags": ['api', 'idor', 'authz'],
        "severity": 'HIGH',
        "cvss_score": 8.0,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Проверять права на каждый объект. Не полагаться только на ID в URL.',
        "references": ['https://owasp.org/API-Security/editions/2019/en/0xa1-broken-object-level-authorization/'],
    },
    5109: {
        "id": 5109,
        "category": 'API',
        "name": 'Missing CSRF Protection',
        "description": 'POST запросы выполняются без CSRF защиты (актуально при cookie-based auth).',
        "check_functions": ['check_api_missing_csrf', 'check_cors_wildcard'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['api', 'csrf'],
        "severity": 'MEDIUM',
        "cvss_score": 6.4,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Использовать CSRF токены и SameSite cookies. Для pure-API предпочтительнее Authorization headers.',
        "references": ['https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html'],
    },
    5110: {
        "id": 5110,
        "category": 'API',
        "name": 'GraphQL Introspection Enabled',
        "description": 'GraphQL introspection доступна и раскрывает схему.',
        "check_functions": ['check_graphql_introspection', 'check_api_info_disclosure'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['api', 'graphql', 'disclosure'],
        "severity": 'HIGH',
        "cvss_score": 7.1,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Ограничить introspection (auth/disable in prod). Добавить query depth limiting.',
        "references": ['https://cheatsheetseries.owasp.org/cheatsheets/GraphQL_Cheat_Sheet.html'],
    },
    5111: {
        "id": 5111,
        "category": 'API',
        "name": 'Verbose Error Messages',
        "description": 'Ошибки API раскрывают stack trace/SQL details, что облегчает эксплуатацию.',
        "check_functions": ['check_api_error_messages', 'check_api_sql_injection'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['api', 'disclosure', 'errors'],
        "severity": 'MEDIUM',
        "cvss_score": 5.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Отключить debug/traceback в production, настроить безопасный error handler.',
        "references": ['https://owasp.org/www-project-top-ten/'],
    },
    5112: {
        "id": 5112,
        "category": 'API',
        "name": 'Swagger Exposed',
        "description": 'Swagger JSON доступен публично.',
        "check_functions": ['check_api_swagger_exposed', 'check_api_info_disclosure'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'swagger'],
        "severity": 'MEDIUM',
        "cvss_score": 4.0,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Защитить swagger endpoints или отключить.',
        "references": ['https://swagger.io/'],
    },
    5113: {
        "id": 5113,
        "category": 'API',
        "name": 'Actuator Exposed',
        "description": 'Spring Boot Actuator endpoint доступен публично и может раскрывать конфигурации.',
        "check_functions": ['check_api_actuator_exposed', 'check_api_info_disclosure'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['api', 'actuator'],
        "severity": 'HIGH',
        "cvss_score": 7.5,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Ограничить доступ к actuator (auth/allowlist) и отключить чувствительные endpoints.',
        "references": ['https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html'],
    },
    5114: {
        "id": 5114,
        "category": 'API',
        "name": 'Debug Endpoints Exposed',
        "description": 'Debug endpoints могут раскрывать внутренние переменные/конфиги.',
        "check_functions": ['check_api_debug_endpoints', 'check_api_error_messages'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 2,
        "depends_on": [],
        "tags": ['api', 'debug'],
        "severity": 'MEDIUM',
        "cvss_score": 6.3,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Отключить debug endpoints в production или защитить аутентификацией.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5115: {
        "id": 5115,
        "category": 'API',
        "name": 'Admin Panels Exposed',
        "description": 'Админ панели доступны публично (возможен обход аутентификации).',
        "check_functions": ['check_api_admin_panels_exposed', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 1,
        "depends_on": [],
        "tags": ['api', 'admin', 'auth'],
        "severity": 'HIGH',
        "cvss_score": 8.2,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Ограничить доступ по allowlist/VPN, добавить MFA и строгую авторизацию.',
        "references": ['https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html'],
    },
    5116: {
        "id": 5116,
        "category": 'API',
        "name": 'Sensitive API Path #01',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_01', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5117: {
        "id": 5117,
        "category": 'API',
        "name": 'Sensitive API Path #02',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_02', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5118: {
        "id": 5118,
        "category": 'API',
        "name": 'Sensitive API Path #03',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_03', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5119: {
        "id": 5119,
        "category": 'API',
        "name": 'Sensitive API Path #04',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_04', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5120: {
        "id": 5120,
        "category": 'API',
        "name": 'Sensitive API Path #05',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_05', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5121: {
        "id": 5121,
        "category": 'API',
        "name": 'Sensitive API Path #06',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_06', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5122: {
        "id": 5122,
        "category": 'API',
        "name": 'Sensitive API Path #07',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_07', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5123: {
        "id": 5123,
        "category": 'API',
        "name": 'Sensitive API Path #08',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_08', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5124: {
        "id": 5124,
        "category": 'API',
        "name": 'Sensitive API Path #09',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_09', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5125: {
        "id": 5125,
        "category": 'API',
        "name": 'Sensitive API Path #10',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_10', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5126: {
        "id": 5126,
        "category": 'API',
        "name": 'Sensitive API Path #11',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_11', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5127: {
        "id": 5127,
        "category": 'API',
        "name": 'Sensitive API Path #12',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_12', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5128: {
        "id": 5128,
        "category": 'API',
        "name": 'Sensitive API Path #13',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_13', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5129: {
        "id": 5129,
        "category": 'API',
        "name": 'Sensitive API Path #14',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_14', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5130: {
        "id": 5130,
        "category": 'API',
        "name": 'Sensitive API Path #15',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_15', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5131: {
        "id": 5131,
        "category": 'API',
        "name": 'Sensitive API Path #16',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_16', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5132: {
        "id": 5132,
        "category": 'API',
        "name": 'Sensitive API Path #17',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_17', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5133: {
        "id": 5133,
        "category": 'API',
        "name": 'Sensitive API Path #18',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_18', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5134: {
        "id": 5134,
        "category": 'API',
        "name": 'Sensitive API Path #19',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_19', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5135: {
        "id": 5135,
        "category": 'API',
        "name": 'Sensitive API Path #20',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_20', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5136: {
        "id": 5136,
        "category": 'API',
        "name": 'Sensitive API Path #21',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_21', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5137: {
        "id": 5137,
        "category": 'API',
        "name": 'Sensitive API Path #22',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_22', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5138: {
        "id": 5138,
        "category": 'API',
        "name": 'Sensitive API Path #23',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_23', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5139: {
        "id": 5139,
        "category": 'API',
        "name": 'Sensitive API Path #24',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_24', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5140: {
        "id": 5140,
        "category": 'API',
        "name": 'Sensitive API Path #25',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_25', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5141: {
        "id": 5141,
        "category": 'API',
        "name": 'Sensitive API Path #26',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_26', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5142: {
        "id": 5142,
        "category": 'API',
        "name": 'Sensitive API Path #27',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_27', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5143: {
        "id": 5143,
        "category": 'API',
        "name": 'Sensitive API Path #28',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_28', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5144: {
        "id": 5144,
        "category": 'API',
        "name": 'Sensitive API Path #29',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_29', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5145: {
        "id": 5145,
        "category": 'API',
        "name": 'Sensitive API Path #30',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_30', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5146: {
        "id": 5146,
        "category": 'API',
        "name": 'Sensitive API Path #31',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_31', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5147: {
        "id": 5147,
        "category": 'API',
        "name": 'Sensitive API Path #32',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_32', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5148: {
        "id": 5148,
        "category": 'API',
        "name": 'Sensitive API Path #33',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_33', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    5149: {
        "id": 5149,
        "category": 'API',
        "name": 'Sensitive API Path #34',
        "description": "Дополнительный вектор: проверка наличия нестандартных/внутренних endpoint'ов.",
        "check_functions": ['check_api_sensitive_path_34', 'check_api_authentication'],
        "requires_adb": False,
        "requires_network": True,
        "priority": 3,
        "depends_on": [],
        "tags": ['api', 'discovery'],
        "severity": 'LOW',
        "cvss_score": 3.7,
        "exploitation_difficulty": 'Medium',
        "remediation": 'Убедиться, что internal endpoints не доступны из внешней сети. Разнести control-plane и data-plane.',
        "references": ['https://owasp.org/www-project-api-security/'],
    },
    }

    return vectors
