"""
D. Supply Chain / Exotic Vectors (171-300)
"""
from typing import Dict, Any


def get_supply_chain_vectors() -> Dict[int, Dict[str, Any]]:
    """Возвращает все Supply Chain / Exotic векторы (171-300)"""
    
    vectors = {}
    
    base_vectors = [
        (171, "OTA Downgrade", "OTA downgrade возможен", "check_ota_downgrade"),
        (172, "OTA MITM", "OTA MITM атака", "check_ota_mitm"),
        (173, "OEM Signature Check", "OEM signature check слабый", "check_oem_signature_check"),
        (174, "Partial Update", "Partial update уязвимость", "check_partial_update"),
        (175, "Differential OTA", "Differential OTA уязвимость", "check_differential_ota"),
        (176, "Firmware Partition Access", "Firmware partition доступ", "check_firmware_partition"),
        (177, "Vendor Blob Backdoors", "Vendor blob бэкдоры", "check_vendor_blob_backdoors"),
        (178, "TrustZone Firmware Age", "TrustZone firmware устаревший", "check_trustzone_firmware_age"),
        (179, "Secure Element Misuse", "Secure element misuse", "check_secure_element_misuse"),
        (180, "eSIM Profile Leak", "eSIM profile утечка", "check_esim_profile_leak"),
        (181, "Baseband Isolation", "Baseband isolation слабая", "check_baseband_isolation"),
        (182, "Modem Crash Leak", "Modem crash утечка", "check_modem_crash_leak"),
        (183, "IMS Service Exposure", "IMS service exposed", "check_ims_service_exposure"),
        (184, "Emergency Service Abuse", "Emergency service abuse", "check_emergency_service_abuse"),
        (185, "Cell Broadcast Abuse", "Cell broadcast abuse", "check_cell_broadcast_abuse"),
        (186, "GNSS Spoofing", "GNSS spoofing возможен", "check_gnss_spoof"),
        (187, "Sensor Fusion Abuse", "Sensor fusion abuse", "check_sensor_fusion_abuse"),
        (188, "Sideband Channel", "Sideband channel утечка", "check_sideband_channel"),
        (189, "USB Descriptor Abuse", "USB descriptor abuse", "check_usb_descriptor_abuse"),
        (190, "USB HID Injection", "USB HID injection", "check_usb_hid_injection"),
        (191, "USB Ethernet", "USB ethernet exposure", "check_usb_ethernet"),
        (192, "USB Debug Class", "USB debug class exposed", "check_usb_debug_class"),
        (193, "Wireless Charging Attack", "Wireless charging атака", "check_wireless_charging"),
        (194, "Power Analysis", "Power analysis возможен", "check_power_analysis"),
        (195, "Acoustic Side Channel", "Acoustic side channel", "check_acoustic_side_channel"),
        (196, "Thermal Side Channel", "Thermal side channel", "check_thermal_side_channel"),
        (197, "Screen Reflection", "Screen reflection атака", "check_screen_reflection"),
        (198, "Camera LED Timing", "Camera LED timing атака", "check_camera_led_timing"),
        (199, "Ambient Light Sensor", "Ambient light sensor утечка", "check_ambient_light"),
        (200, "Voice Assistant Abuse", "Voice assistant abuse", "check_voice_assistant_abuse"),
        (201, "Wake Word Spoofing", "Wake word spoofing", "check_wake_word_spoof"),
        (202, "Offline Assistant Abuse", "Offline assistant abuse", "check_offline_assistant_abuse"),
        (203, "Speech Model Leak", "Speech model утечка", "check_speech_model_leak"),
        (204, "Face Unlock Spoofing", "Face unlock spoofing", "check_face_unlock_spoof"),
        (205, "Biometric Fallback Abuse", "Biometric fallback abuse", "check_biometric_fallback_abuse"),
        (206, "Liveness Detection", "Liveness detection слабая", "check_liveness_detection"),
        (207, "Secure Folder Escape", "Secure folder escape", "check_secure_folder_escape"),
        (208, "Work Profile Isolation", "Work profile isolation слабая", "check_work_profile_isolation"),
        (209, "MDM Misconfiguration", "MDM неправильно настроен", "check_mdm_misconfig"),
        (210, "Enterprise Policy Bypass", "Enterprise policy bypass", "check_enterprise_policy_bypass"),
        (211, "Knox Container Escape", "Knox container escape", "check_knox_container_escape"),
        (212, "Virtualization Exposure", "Virtualization exposed", "check_virtualization_exposure"),
        (213, "Android Hypervisor Config", "Android hypervisor конфигурация", "check_android_hypervisor_config"),
        (214, "VM Escape", "VM escape возможен", "check_vm_escape"),
        (215, "GPU Driver Attack", "GPU driver атака", "check_gpu_driver_attack"),
        (216, "NPU Driver Attack", "NPU driver атака", "check_npu_driver_attack"),
        (217, "DSP Driver Attack", "DSP driver атака", "check_dsp_driver_attack"),
        (218, "Sensor Hub Firmware", "Sensor hub firmware уязвимость", "check_sensor_hub_firmware"),
        (219, "Wear OS Bridge", "Wear OS bridge уязвимость", "check_wear_os_bridge"),
        (220, "Automotive HAL", "Automotive HAL exposure", "check_automotive_hal"),
        (221, "Smart Home Bridge", "Smart home bridge уязвимость", "check_smart_home_bridge"),
        (222, "Cross Device Trust", "Cross device trust слабый", "check_cross_device_trust"),
        (223, "Nearby Share Abuse", "Nearby share abuse", "check_nearby_share_abuse"),
        (224, "UWB Misuse", "Ultra-wideband misuse", "check_uwidthband_misuse"),
        (225, "UWB Ranging Spoof", "UWB ranging spoofing", "check_uwb_ranging_spoof"),
        (226, "Emergency SOS Abuse", "Emergency SOS abuse", "check_emergency_sos_abuse"),
        (227, "Location History", "Location history утечка", "check_location_history"),
        (228, "Timeline Inference", "Timeline inference", "check_timeline_inference"),
        (229, "AI Suggestion Leak", "AI suggestion утечка", "check_ai_suggestion_leak"),
        (230, "Contextual Service Abuse", "Contextual service abuse", "check_contextual_service_abuse"),
        (231, "System Intelligence Leak", "System intelligence утечка", "check_system_intelligence_leak"),
        (232, "Federated Learning Leak", "Federated learning утечка", "check_federated_learning_leak"),
        (233, "On-Device Training Leak", "On-device training утечка", "check_on_device_training_leak"),
        (234, "Model Update Poisoning", "Model update poisoning", "check_model_update_poisoning"),
        (235, "Offline Update Poisoning", "Offline update poisoning", "check_offline_update_poisoning"),
        (236, "Sideloaded Firmware", "Sideloaded firmware", "check_sideloaded_firmware"),
        (237, "Refurbished Residue", "Refurbished residue данные", "check_refurbished_residue"),
        (238, "Factory Reset Residue", "Factory reset residue", "check_factory_reset_residue"),
        (239, "FRP Logic Weakness", "FRP logic слабость", "check_frp_logic_weakness"),
        (240, "Google Account Bypass", "Google account bypass", "check_google_account_bypass"),
        (241, "Anti-Theft Logic", "Anti-theft logic слабость", "check_anti_theft_logic"),
        (242, "Lost Mode Bypass", "Lost mode bypass", "check_lost_mode_bypass"),
        (243, "Remote Wipe Bypass", "Remote wipe bypass", "check_remote_wipe_bypass"),
        (244, "Data Remanence", "Data remanence", "check_data_remanence"),
        (245, "Flash Wear Leveling", "Flash wear leveling утечка", "check_flash_wear_leveling"),
        (246, "NAND Remap", "NAND remap уязвимость", "check_nand_remap"),
        (247, "JTAG Proximity", "JTAG доступен", "check_jtag_proximity"),
        (248, "UART Exposure", "UART exposed", "check_uart_exposure"),
        (249, "Test Point Exposure", "Test point exposed", "check_test_point_exposure"),
        (250, "Boot ROM Exploit", "Boot ROM exploit", "check_boot_rom_exploit"),
        (251, "Mask ROM Version", "Mask ROM version уязвимость", "check_mask_rom_version"),
        (252, "SoC Revision Flaws", "SoC revision flaws", "check_soc_revision_flaws"),
        (253, "Silicon Errata", "Silicon errata", "check_silicon_errata"),
        (254, "Cold Boot Attack", "Cold boot атака", "check_cold_boot"),
        (255, "RAM Remanence", "RAM remanence", "check_ram_remanence"),
        (256, "Rowhammer", "Rowhammer уязвимость", "check_rowhammer"),
        (257, "DRAM TRR Weakness", "DRAM TRR слабость", "check_dram_trr_weakness"),
        (258, "Cache Eviction", "Cache eviction атака", "check_cache_eviction"),
        (259, "CPU Speculative Leak", "CPU speculative execution утечка", "check_cpu_speculative_leak"),
        (260, "ARM Errata", "ARM errata", "check_arm_errata"),
        (261, "PAC Bypass", "PAC bypass", "check_pac_bypass"),
        (262, "MTE Disabled", "MTE disabled", "check_mte_disabled"),
        (263, "Shadow Stack Absent", "Shadow stack отсутствует", "check_shadow_stack_absent"),
        (264, "Control Flow Integrity", "CFI слабый", "check_control_flow_integrity"),
        (265, "Pointer Authentication", "Pointer authentication слабый", "check_pointer_authentication"),
        (266, "Spectre Mitigation", "Spectre mitigation отсутствует", "check_spectre_mitigation"),
        (267, "Meltdown Mitigation", "Meltdown mitigation отсутствует", "check_meltdown_mitigation"),
        (268, "Transient Execution", "Transient execution уязвимость", "check_transient_execution"),
        (269, "Browser Sandbox Escape", "Browser sandbox escape", "check_browser_sandbox_escape"),
        (270, "WebGPU Isolation", "WebGPU isolation слабая", "check_webgpu_isolation"),
        (271, "WebAssembly JIT", "WebAssembly JIT уязвимость", "check_webassembly_jit"),
        (272, "PDF.js Sandbox", "PDF.js sandbox слабый", "check_pdf_js_sandbox"),
        (273, "Font Parser", "Font parser уязвимость", "check_font_parser"),
        (274, "Emoji Font Exploit", "Emoji font exploit", "check_emoji_font_exploit"),
        (275, "OEM Emoji Engine", "OEM emoji engine уязвимость", "check_oem_emoji_engine"),
        (276, "Vendor Keyboard Telemetry", "Vendor keyboard telemetry", "check_vendor_keyboard_telemetry"),
        (277, "Keyboard Inference", "Keyboard inference", "check_keyboard_inference"),
        (278, "Touch Timing", "Touch timing атака", "check_touch_timing"),
        (279, "Haptic Feedback", "Haptic feedback утечка", "check_haptic_feedback"),
        (280, "Screen Refresh Rate", "Screen refresh rate утечка", "check_screen_refresh"),
        (281, "Always On Display", "Always on display утечка", "check_always_on_display"),
        (282, "Lockscreen Notification", "Lockscreen notification утечка", "check_lockscreen_notification"),
        (283, "Smart Reply", "Smart reply утечка", "check_smart_reply"),
        (284, "Screenshot AI Cache", "Screenshot AI cache утечка", "check_screenshot_ai_cache"),
        (285, "Voice Typing Buffer", "Voice typing buffer утечка", "check_voice_typing_buffer"),
        (286, "Offline Dictation", "Offline dictation утечка", "check_offline_dictation"),
        (287, "Clipboard ML Cache", "Clipboard ML cache утечка", "check_clipboard_ml_cache"),
        (288, "On-Device OCR Cache", "On-device OCR cache утечка", "check_on_device_ocr_cache"),
        (289, "Smart Photo Analysis", "Smart photo analysis утечка", "check_smart_photo_analysis"),
        (290, "Gallery ML Metadata", "Gallery ML metadata утечка", "check_gallery_ml_metadata"),
        (291, "EXIF Location", "EXIF location утечка", "check_exif_location"),
        (292, "Sensor Calibration", "Sensor calibration утечка", "check_sensor_calibration"),
        (293, "Factory Test Artifacts", "Factory test artifacts", "check_factory_test_artifacts"),
        (294, "Diagnostic App Residue", "Diagnostic app residue", "check_diagnostic_app_residue"),
        (295, "Engineering APK Residue", "Engineering APK residue", "check_engineering_apk_residue"),
        (296, "OEM Hidden APKs", "OEM hidden APKs", "check_oem_hidden_apks"),
        (297, "Debug Certificates", "Debug certificates", "check_debug_certificates"),
        (298, "Signing Key Reuse", "Signing key reuse", "check_signing_key_reuse"),
        (299, "Dev Provisioning Profiles", "Dev provisioning profiles", "check_dev_provisioning_profiles"),
        (300, "Undocumented OEM Vector", "Undocumented OEM vector", "check_undocumented_oem_vector"),
    ]
    
    for vector_id, name, description, check_func in base_vectors:
        vectors[vector_id] = {
            "id": vector_id,
            "category": "D",
            "name": name,
            "description": description,
            "check_function": check_func,
            "requires_adb": True,
            "requires_network": False,
            "priority": 4,
            "depends_on": [6],
            "tags": ["supply-chain", "exotic", "advanced"],
        }
    
    return vectors
